name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        registry-url: https://npm.fontawesome.com
        scope: '@fortawesome'

    - name: Install dependencies
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_FORTAWESOME_TOKEN}}
        
    - name: Build
      run: npm run build

    - name: Deploy to BunnyCDN
      uses: ayeressian/bunnycdn-storage-deploy@master
      with:
        source: "public"
        storageZoneName: "start-brams-dev"
        accessKey: "${{ secrets.BUNNY_CDN_STORAGE_KEY }}"